# CONFIGURACIÓN DE LA APLICACIÓN #


# NOMBRE DE LA APP
spring.application.name=logitrack


# =============================================================
# BASE DE DATOS ? MySQL
# =============================================================

# URL de conexión a la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/logitrack_db

# Usuario de MySQL
spring.datasource.username=root

# Contraseña de MySQL
spring.datasource.password=leavemealone09

# Driver de MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =============================================================
# JPA / HIBERNATE
# =============================================================

# Muestra las consultas SQL en consola ? útil para depurar
spring.jpa.show-sql=true

# Formatea el SQL en consola para que sea más legible
spring.jpa.properties.hibernate.format_sql=true

# validate ? Hibernate verifica que el modelo coincida con la DB
# pero NO modifica la DB. El schema.sql ya la creó.
spring.jpa.hibernate.ddl-auto=none


# =============================================================
# SERVIDOR
# =============================================================

# Puerto donde corre la aplicación
server.port=8080

# =============================================================
# SWAGGER
# =============================================================

# Ruta donde estará disponible la documentación
springdoc.swagger-ui.path=/swagger-ui.html

springdoc.api-docs.enabled=true
springdoc.writer-with-default-pretty-printer=true

# -- Para permitir que ingresen de cualquier dispositivo (evitando firewall, etc). --
server.address=0.0.0.0
